version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - frents

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - frents

  apollo:
    image: node:10
    container_name: graphql
    ports:
      - 4000:4000
    networks:
      - frents
    working_dir: /root/apps/backend
    entrypoint: yarn start
    volumes:
      - ../../backend:/root/apps/backend

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - frents
    expose:
      - 6379

networks:
  frents: