version: 2.1

project_base_path: &project_base_path /frents
circleci_container: &circleci_container
  docker:
    - image: circleci/node:10

jobs:
  lint:
    <<: *circleci_container
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache_packages_backend{{ checksum "./backend/package.json" }}
      - run:
          name: "[BE] Install"
          command: yarn --cwd ./backend install
      - run:
          name: "[BE] Run lint"
          command: yarn --cwd ./backend code:lint:check
      - save_cache:
          paths:
            - ./backend/node_modules
          key: cache_packages_backend{{ checksum "./backend/package.json" }}

  prettify:
    <<: *circleci_container
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache_packages_backend{{ checksum "./backend/package.json" }}
      - run:
          name: "[BE] Install"
          command: yarn --cwd ./backend install
      - run:
          name: "[BE] Run prettier"
          command: yarn --cwd ./backend code:prettier:check
      - save_cache:
          paths:
            - ./backend/node_modules
          key: cache_packages_backend{{ checksum "./backend/package.json" }}


workflows:
  version: 2
  build:
    jobs:
      - lint
      - prettify